### ISSUE TITLE
Question about recurrenting MATNet

### ISSUE THREAD

**Issue by DUT-CSJ** [CODE4UVOS/HFAN#1]

**Comment by DUT-CSJ** [comment]
Hello, I wanna know optimizer and hyperparameters you use when recurrenting MATNet.
Hope for your reply!

**Comment by CODE4UVOS** [comment]
Thanks for your attention.
We have used the same optimizer and its accompanying hyperparameters.

See L133-L233 in ` local_config/hfan/hfan.*.py`.

**Comment by CODE4UVOS** [comment]
Thanks for your attention.
We have used the same optimizer and its accompanying hyperparameters.

See L92-L103  in local_config/hfan/hfan.*.py.

**Comment by DUT-CSJ** [comment]
> Thanks for your attention. We have used the same optimizer and its accompanying hyperparameters.
> 
> See L92-L103 in local_config/hfan/hfan.*.py.

Thank you very much!
