### ISSUE TITLE
How many backbones does HFAN use?

### ISSUE THREAD

**Issue by DUT-CSJ** [CODE4UVOS/HFAN#3]
Hello, as we know, previous optical flow-based UVOS methods usually use two backbones to extract features from image and optical flow, respectively. However, I check your code and find that maybe HFAN only use a single backbone to extract both the image and optical flow features.
Maybe I misunderstand the code, so I wanna know how many backbones does HFAN use? A single backbone to extract image and optical flow or two backbones to extract image and optical flow, respectively?
Looking forward to your reply.

**Comment by CODE4UVOS** [comment]
As far as I know, previous works use multiple backbones that shared weights. We superimpose an image and optical flow and feed them into one backbone, which has the same effect as existing methods.

In lines 34 to 38 of hfan_vos.py, merge_batches can be expressed as (image BxCxHxW, flow BxCxHxW) -> image-flow 2BxCxHxW.

**Comment by DUT-CSJ** [comment]
> 

But... Some methods such as MATNet, AMC-Net and APS use two same backbones which do not share weights. So I think HFAN may get better performance when employing two backbones.
According to my observation, the inter-frame based methods use the shared-weight backbone, while the optical-flow-based methods usually use two same backbones. Are you sure 'previous works use multiple backbones that shared weights.'?

**Comment by DUT-CSJ** [comment]
> 

But... Some methods such as MATNet, AMC-Net and APS use two same backbones which do not share weights. So I think HFAN may get better performance when employing two backbones.
According to my observation, the inter-frame based methods use the shared-weight backbone, while the optical-flow-based methods usually use two same backbones. Are you sure 'previous works use multiple backbones that shared weights.'?

**Comment by CODE4UVOS** [comment]
Thank you for your reply. As you said, the optical flow based methods share the network structure but not the parameters.

We used the same network structure and parameters to align the appearance and motion features and did not try a non-shared parameter backbone. Thank you again for the suggestion, and we will try this solution in a subsequent extended version.

**Comment by DUT-CSJ** [comment]
> Thank you for your reply. As you said, the optical flow based methods share the network structure but not the parameters.
> 
> We used the same network structure and parameters to align the appearance and motion features and did not try a non-shared parameter backbone. Thank you again for the suggestion, and we will try this solution in a subsequent extended version.

Thank you for your reply.
